### ISSUE TITLE
 'pattern reloaded' ParisJUG, june 2015

### ISSUE THREAD

**Issue by eheb** [forax/design-pattern-reloaded#8]
Remy, I only find this solution to communicate with you. Sorry...
your  talk  'pattern reloaded' ParisJUG, june 2015 is very fun !!! and very hard
-> 2 typos: slide Abstract Factory Impl : fun -> supplier (2 times)
And in slide 'higher order function inBetween(0,50)::test
1 question please : how to debug a lambda expression ?

**Comment by forax** [comment]
Hi,
thanks for the typos, i will fix them

> how to debug a lambda expression ?
> You can put a breakpoint in it like any Java code
> (you need a recent version of your IDE because both Eclipse and IntelliJ IDEA had bugs making the debugging process more painful that it should)

BTW, if the lambda is too complex, it just means that you should extract the code to a method and call that method from the body of the lambda (you can also use the method reference syntax as a shortcut). 

If it's the lambda object i.e. the instance of a functional interface after the lambda conversion,
it's a little harder because there is no obvious link between the object and the lambda body (apart when you execute it). A lambda is immutable, so no way to add information in it and you can not change the toString() of a lambda by overriding the toString of the corresponding functional interface.
